version: 2
updates:
- package-ecosystem: github-actions
  directories: 
    - "/"
    - "/.github/actions/build-and-test/"
    - "/.github/actions/deploy/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
  groups:
    github_action-dependencies:
      patterns:
        - "*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
  groups:
    npm-dependencies:
      patterns:
        - "*"
