version: 2

always_pending:
  title_regex: '(WIP|wip)'
  labels:
    - wip
  explanation: 'This PR is a work in progress...'

group_defaults:
  reset_on_push:
    enabled: true
  reject_value: -2
  approve_regex: '^(Approved|:shipit:|:\+1:|Engage)'
  reject_regex: '^(Rejected|:-1:|Borg)'
  author_approval:
    auto: true

groups:
  development:
    approve_by_comment:
      enabled: true
    conditions:
      branches:
        - development
    required: 2
    teams:
      - approvers

  master:
    approve_by_comment:
      enabled: true
    conditions:
      branches:
        - master
    required: 4
    teams:
      - admin
