openapi: 3.0.2
components:
  paths:
    client:
      summary: Modify client
      parameters:
        - $ref: '#/components/parameters/client'
      get:
        summary: Get clients
        tags:
          - "Client management"
        operationId: "get_clients"
        description: |
          `{client}` is optional. Specifying it will result in only the requested client being returned.

          Valid combinations are:
          - `/api/clients` (all clients)
          - `/api/clients/my_client` (client identical to `my_client`)
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/clients/get'
                examples:
                  - $ref: '#/components/examples/clients'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
      put:
        summary: Replace client
        tags:
          - "Client management"
        operationId: "replace_client"
        description: |
          Items may be updated by replacing them. `{client}` is required.

          Ensure to send all the required parameters (such as `comment` or `groups`) to ensure these properties are retained.
          The read-only fields `id` and `date_added` are preserved, `date_modified` is automatically updated on success.
        requestBody:
          description: Callback payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clients/put'
        responses:
          '201':
            description: Created item
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/clients/get' # identical to GET
          '400':
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/bad_request'
                examples:
                  - $ref: '#/components/examples/errors/uri_error/item_missing'
                  - $ref: '#/components/examples/errors/bad_request/no_payload'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
      delete:
        summary: Delete client
        tags:
          - "Client management"
        operationId: "delete_client"
        description: |
          *Note:* There will be no content on success.
        responses:
          '204':
            description: Item deleted
          '400':
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/bad_request'
                examples:
                  - $ref: '#/components/examples/errors/uri_error/item_missing'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
    direct:
      post:
        summary: Add new client
        tags:
          - "Client management"
        operationId: "add_client"
        description: |
          Creates a new client in the `clients` object. The `{client}` itself is specified in the request body (POST JSON).

          Clients may be described either by their IP addresses (IPv4 and IPv6 are supported),
          IP subnets (CIDR notation, like `192.168.2.0/24`), their MAC addresses (like `12:34:56:78:9A:BC`), by their hostnames (like `localhost`), or by the interface they are connected to (prefaced with a colon, like `:eth0`).</p>

          Note that client recognition by IP addresses (incl. subnet ranges) is prefered over MAC address, host name or interface recognition as the two latter will only be available after some time.
          Furthermore, MAC address recognition only works for devices at most one networking hop away from your Pi-hole.

          On success, a new ressource is created at `/clients/{client}`.

          The `database_error` with message `UNIQUE contraint failed` error indicates that this client already exists.
        requestBody:
          description: Callback payload
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/clients/post'
        responses:
          '201':
            description: Created item
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/clients/get' # identical to GET
          '400':
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/bad_request'
                examples:
                  - $ref: '#/components/examples/errors/bad_request/no_payload'
                  - $ref: '#/components/examples/errors/database_error/duplicate'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: 'common.yaml#/components/errors/unauthorized'
  schemas:
    clients:
      get:
        type: object
        properties:
          clients:
            type: array
            items:
              allOf:
                - $ref: '#/components/schemas/client'
                - $ref: '#/components/schemas/comment'
                - $ref: '#/components/schemas/groups'
                - $ref: '#/components/schemas/readonly'
      post:
        allOf:
          - $ref: '#/components/schemas/client'
          - $ref: '#/components/schemas/comment'
          - $ref: '#/components/schemas/groups'
      put:
        allOf:
          - $ref: '#/components/schemas/comment'
          - $ref: '#/components/schemas/groups'
    client:
      type: object
      properties:
        client:
          description: client IP / MAC / hostname / interface
          type: string
          required: true
          example: 127.0.0.1
    comment:
      type: object
      properties:
        comment:
          description: User-provided free-text comment for this client (may be `null` if not specified)
          type: string
          required: false
          nullable: true
          default: null
          example: Some comment for this client
    name:
      type: object
      properties:
        name:
          description: hostname (only available when {client} is an IP address)
          type: string
          readOnly: true
          example: localhost
    groups:
      type: object
      properties:
        groups:
          description: Array of group IDs
          type: array
          default: [0]
          required: false
          items:
            type: integer
    readonly:
      type: object
      summary: Readonly properties of a single client
      properties:
        id:
          description: Database ID
          type: integer
          readOnly: true
          example: 1
        date_added:
          description: Unix timestamp of item addition
          type: integer
          readOnly: true
          example: 1611239095
        date_modified:
          description: Unix timestamp of last item modification
          type: integer
          readOnly: true
          example: 1611239099
  examples:
    clients:
      name: Example clients
      value:
        clients:
          - client: "127.0.0.1"
            name: "localhost"
            comment: "comment"
            id: 1
            date_added: 1604871899
            date_modified: 1604871899
          - client: "::1"
            name: "ip6-localhost"
            comment: null
            id: 2
            date_added: 1611322675
            date_modified: 1611325497
    errors:
      uri_error:
        item_missing:
          summary: Client to be modified is missing
          value:
            error:
              key: "uri_error"
              message: "Invalid request: Specify item in URI"
              hint: null
      bad_request:
        no_payload:
          summary: No JSON payload found
          value:
            error:
              key: "bad_request"
              message: "Invalid request body data (no valid JSON)"
              hint: null
      database_error:
        duplicate:
          summary: Database error
          value:
            error:
              key: "database_error"
              message: "Could not add to gravity database"
              hint: "UNIQUE constraint failed: clientlist.client"
  parameters:
    client:
      in: path
      name: client
      schema:
        type: string
      required: true
      description: client IP / MAC / hostname / interface
      example: 127.0.0.1
